### ISSUE TITLE
vuejs3 compatibility

### ISSUE THREAD

**Issue by Modex987** [dmtrbrl/vue-trend-chart#18]
since chartjs is not compatible with vue3 vue-trend-chart also has some problems when it's used with vue3 like the h function, i solved the h function issue but still see a lot of problems , is there any future fix for this , &thank you

**Comment by dmtrbrl** [comment]
Hi @Modex987. Thanks for the question.
This library was written a while ago and yes, I'm planning  to update it in the future. But at the moment I can't say when exactly

**Comment by Modex987** [comment]
Hi @dmtrbrl thank you so much i actually had success with chartjs and vue3 i made it work i used the separately
