### ISSUE TITLE
Changing xLabels doesn't update the HTML

### ISSUE THREAD

**Issue by SebastianSpeitel** [dmtrbrl/vue-trend-chart#6]
When changing xLabels, by changing it on TrendChartLabels directly or via TrendChart, the HTML doesn't get rerendered.

I build a workaround by calling $forceReload everytime I update it, but there has to be a better solution.

**Comment by dmtrbrl** [comment]
Hi @SebastianSpeitel 
Could you provide an example?
jsfiddle or codepen would be nice

**Comment by dmtrbrl** [comment]
Fixed. See example on the demo page
